-- Haskell module generated by the BNF converter

module TidyParser.Skel where

import qualified TidyParser.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transUpperCaseIdent :: TidyParser.Abs.UpperCaseIdent -> Result
transUpperCaseIdent x = case x of
  TidyParser.Abs.UpperCaseIdent string -> failure x
transLowerCaseIdent :: TidyParser.Abs.LowerCaseIdent -> Result
transLowerCaseIdent x = case x of
  TidyParser.Abs.LowerCaseIdent string -> failure x
transProgram :: TidyParser.Abs.Program -> Result
transProgram x = case x of
  TidyParser.Abs.ProgramEntrypoint classdecls -> failure x
transClassIdent :: TidyParser.Abs.ClassIdent -> Result
transClassIdent x = case x of
  TidyParser.Abs.CIdent uppercaseident -> failure x
transClassDecl :: TidyParser.Abs.ClassDecl -> Result
transClassDecl x = case x of
  TidyParser.Abs.ClassDeclConcrete classtype classident inheritance classbody -> failure x
  TidyParser.Abs.ClassDeclAbstract classtype classident inheritance classbody -> failure x
transInheritance :: TidyParser.Abs.Inheritance -> Result
transInheritance x = case x of
  TidyParser.Abs.SuperclassAbsent -> failure x
  TidyParser.Abs.SuperclassPresent classident -> failure x
transClassBody :: TidyParser.Abs.ClassBody -> Result
transClassBody x = case x of
  TidyParser.Abs.ClassBodyEmpty -> failure x
  TidyParser.Abs.ClassBodyFilled valuessection variablessection functionssection actionssection -> failure x
transClassType :: TidyParser.Abs.ClassType -> Result
transClassType x = case x of
  TidyParser.Abs.MMutable -> failure x
  TidyParser.Abs.MImmutable -> failure x
  TidyParser.Abs.MSingleton -> failure x
transValuesSection :: TidyParser.Abs.ValuesSection -> Result
transValuesSection x = case x of
  TidyParser.Abs.ValuesAbsent -> failure x
  TidyParser.Abs.ValuesPresent valsbody -> failure x
transVariablesSection :: TidyParser.Abs.VariablesSection -> Result
transVariablesSection x = case x of
  TidyParser.Abs.VariablesAbsent -> failure x
  TidyParser.Abs.VariablesPresent varsbody -> failure x
transFunctionsSection :: TidyParser.Abs.FunctionsSection -> Result
transFunctionsSection x = case x of
  TidyParser.Abs.FunctionsAbsent -> failure x
  TidyParser.Abs.FunctionsPresent fsbody -> failure x
transActionsSection :: TidyParser.Abs.ActionsSection -> Result
transActionsSection x = case x of
  TidyParser.Abs.ActionsAbsent -> failure x
  TidyParser.Abs.ActionsPresent asbody -> failure x
transValSBody :: TidyParser.Abs.ValSBody -> Result
transValSBody x = case x of
  TidyParser.Abs.ValSBodyOneLine valuedecls -> failure x
  TidyParser.Abs.ValSBodyMultiLine valuedecls -> failure x
transValueIdent :: TidyParser.Abs.ValueIdent -> Result
transValueIdent x = case x of
  TidyParser.Abs.VIdent lowercaseident -> failure x
transValueType :: TidyParser.Abs.ValueType -> Result
transValueType x = case x of
  TidyParser.Abs.ValueTypeClass classident -> failure x
  TidyParser.Abs.ValueTypeGeneric classident classidents -> failure x
  TidyParser.Abs.ValueTypeFunction methodtype -> failure x
  TidyParser.Abs.ValueTypeAction methodtype -> failure x
transValueDecl :: TidyParser.Abs.ValueDecl -> Result
transValueDecl x = case x of
  TidyParser.Abs.PublicValueDecl valuedeclproper -> failure x
  TidyParser.Abs.PrivateValueDecl valuedeclproper -> failure x
transValueDeclProper :: TidyParser.Abs.ValueDeclProper -> Result
transValueDeclProper x = case x of
  TidyParser.Abs.UninitialisedValue valueident valuetype -> failure x
  TidyParser.Abs.InitialisedValue valueident valuetype expr -> failure x
transVarSBody :: TidyParser.Abs.VarSBody -> Result
transVarSBody x = case x of
  TidyParser.Abs.VarSBodyOneLine valuedecls -> failure x
  TidyParser.Abs.VarSBodyMultiLine valuedecls -> failure x
transFSBody :: TidyParser.Abs.FSBody -> Result
transFSBody x = case x of
  TidyParser.Abs.FSBodyEmpty -> failure x
  TidyParser.Abs.FSBodyFilled functiondecls -> failure x
transFunctionIdent :: TidyParser.Abs.FunctionIdent -> Result
transFunctionIdent x = case x of
  TidyParser.Abs.FIdent lowercaseident -> failure x
transMethodType :: TidyParser.Abs.MethodType -> Result
transMethodType x = case x of
  TidyParser.Abs.FType valuedecls valuetype -> failure x
transFunctionDecl :: TidyParser.Abs.FunctionDecl -> Result
transFunctionDecl x = case x of
  TidyParser.Abs.OverrideFunctionDecl functionident methodtype functionbody -> failure x
  TidyParser.Abs.PublicFunctionDecl functionident methodtype functionbody -> failure x
  TidyParser.Abs.PrivateFunctionDecl functionident methodtype functionbody -> failure x
transFunctionBody :: TidyParser.Abs.FunctionBody -> Result
transFunctionBody x = case x of
  TidyParser.Abs.FunctionBodyOneLine expr -> failure x
  TidyParser.Abs.FunctionBodyMultiLine expr withvalues -> failure x
transWithValues :: TidyParser.Abs.WithValues -> Result
transWithValues x = case x of
  TidyParser.Abs.WithValuesAbsent -> failure x
  TidyParser.Abs.WithValuesPresent valuessection -> failure x
transASBody :: TidyParser.Abs.ASBody -> Result
transASBody x = case x of
  TidyParser.Abs.ASBodyEmpty -> failure x
  TidyParser.Abs.ASBodyFilled actiondecls -> failure x
transActionDecl :: TidyParser.Abs.ActionDecl -> Result
transActionDecl x = case x of
  TidyParser.Abs.OverrideActionDecl functionident methodtype actionbody -> failure x
  TidyParser.Abs.PublicActionDecl functionident methodtype actionbody -> failure x
  TidyParser.Abs.PrivateActionDecl functionident methodtype actionbody -> failure x
transActionBody :: TidyParser.Abs.ActionBody -> Result
transActionBody x = case x of
  TidyParser.Abs.ActionBodyOneLine expr -> failure x
  TidyParser.Abs.ActionBodyMultiLine exprs -> failure x
transExpr :: TidyParser.Abs.Expr -> Result
transExpr x = case x of
  TidyParser.Abs.ELiteral literal -> failure x
  TidyParser.Abs.ELocalValue valueident -> failure x
  TidyParser.Abs.ELocalValueDecl localvaluedecl -> failure x
  TidyParser.Abs.ELambdaFunction lambdafunction -> failure x
  TidyParser.Abs.ELambdaAction lambdaaction -> failure x
  TidyParser.Abs.ELocalFunctionCall functioncall -> failure x
  TidyParser.Abs.ELocalActionCall functioncall -> failure x
  TidyParser.Abs.ECtorCall constructorcall -> failure x
  TidyParser.Abs.EGetExpr getexpr -> failure x
  TidyParser.Abs.EDoExpr doexpr -> failure x
  TidyParser.Abs.EImperativeControlFlow imperativecontrolflow -> failure x
  TidyParser.Abs.EFunctionalControlFlow functionalcontrolflow -> failure x
  TidyParser.Abs.EUnaryNot expr -> failure x
  TidyParser.Abs.EUnaryMinus expr -> failure x
  TidyParser.Abs.EMultiply expr1 expr2 -> failure x
  TidyParser.Abs.EDivide expr1 expr2 -> failure x
  TidyParser.Abs.EAdd expr1 expr2 -> failure x
  TidyParser.Abs.ESubtract expr1 expr2 -> failure x
  TidyParser.Abs.EConcatenate expr1 expr2 -> failure x
  TidyParser.Abs.ERelationalOperator expr1 relationaloperator expr2 -> failure x
  TidyParser.Abs.EBooleanOperator expr1 booleanoperator expr2 -> failure x
transLiteral :: TidyParser.Abs.Literal -> Result
transLiteral x = case x of
  TidyParser.Abs.LInt integer -> failure x
  TidyParser.Abs.LBool boolean -> failure x
  TidyParser.Abs.LChar char -> failure x
  TidyParser.Abs.LString string -> failure x
  TidyParser.Abs.LVoid void -> failure x
transBoolean :: TidyParser.Abs.Boolean -> Result
transBoolean x = case x of
  TidyParser.Abs.BTrue -> failure x
  TidyParser.Abs.BFalse -> failure x
transVoid :: TidyParser.Abs.Void -> Result
transVoid x = case x of
  TidyParser.Abs.VPass -> failure x
transLocalValueDecl :: TidyParser.Abs.LocalValueDecl -> Result
transLocalValueDecl x = case x of
  TidyParser.Abs.LocalVDecl valuedecl -> failure x
transLambdaFunction :: TidyParser.Abs.LambdaFunction -> Result
transLambdaFunction x = case x of
  TidyParser.Abs.LambdaFunctionOneLine valuedecls expr -> failure x
  TidyParser.Abs.LambdaFunctionMultiLine valuedecls expr -> failure x
transLambdaAction :: TidyParser.Abs.LambdaAction -> Result
transLambdaAction x = case x of
  TidyParser.Abs.LambdaActionOneLine valuedecls expr -> failure x
  TidyParser.Abs.LambdaActionMultiLine valuedecls expr -> failure x
transFunctionCall :: TidyParser.Abs.FunctionCall -> Result
transFunctionCall x = case x of
  TidyParser.Abs.FunctionCallNoArgs functionident -> failure x
  TidyParser.Abs.FunctionCallWithArgs functionident functionarguments -> failure x
transFunctionArgument :: TidyParser.Abs.FunctionArgument -> Result
transFunctionArgument x = case x of
  TidyParser.Abs.FunctionArg expr -> failure x
transConstructorCall :: TidyParser.Abs.ConstructorCall -> Result
transConstructorCall x = case x of
  TidyParser.Abs.CtorCallNoArgs classident -> failure x
  TidyParser.Abs.CtorCallWithArgs classident functionarguments -> failure x
transGetExpr :: TidyParser.Abs.GetExpr -> Result
transGetExpr x = case x of
  TidyParser.Abs.GetExprInstance valueident functioncall -> failure x
  TidyParser.Abs.GetExprStatic classident functioncall -> failure x
  TidyParser.Abs.GetExprChain getexpr functioncall -> failure x
transDoExpr :: TidyParser.Abs.DoExpr -> Result
transDoExpr x = case x of
  TidyParser.Abs.DoExprInstance valueident functioncall -> failure x
  TidyParser.Abs.DoExprStatic classident functioncall -> failure x
  TidyParser.Abs.DoExprChain getexpr functioncall -> failure x
transImperativeControlFlow :: TidyParser.Abs.ImperativeControlFlow -> Result
transImperativeControlFlow x = case x of
  TidyParser.Abs.IWhile expr exprs -> failure x
  TidyParser.Abs.IForeach valuedecl expr exprs -> failure x
  TidyParser.Abs.IIf expr exprs optionalelsebranch -> failure x
transOptionalElseBranch :: TidyParser.Abs.OptionalElseBranch -> Result
transOptionalElseBranch x = case x of
  TidyParser.Abs.ElsePresent exprs -> failure x
  TidyParser.Abs.ElseAbsent -> failure x
transFunctionalControlFlow :: TidyParser.Abs.FunctionalControlFlow -> Result
transFunctionalControlFlow x = case x of
  TidyParser.Abs.FIfThenElse expr thenbranch elsebranch -> failure x
  TidyParser.Abs.FMatch expr matchcases -> failure x
transThenBranch :: TidyParser.Abs.ThenBranch -> Result
transThenBranch x = case x of
  TidyParser.Abs.ThenOneLine expr -> failure x
  TidyParser.Abs.ThenMultiLine expr -> failure x
transElseBranch :: TidyParser.Abs.ElseBranch -> Result
transElseBranch x = case x of
  TidyParser.Abs.ElseOneLine expr -> failure x
  TidyParser.Abs.ElseMultiLine expr -> failure x
transMatchCase :: TidyParser.Abs.MatchCase -> Result
transMatchCase x = case x of
  TidyParser.Abs.Case pattern_ expr -> failure x
transPattern :: TidyParser.Abs.Pattern -> Result
transPattern x = case x of
  TidyParser.Abs.TypePattern classident -> failure x
transRelationalOperator :: TidyParser.Abs.RelationalOperator -> Result
transRelationalOperator x = case x of
  TidyParser.Abs.RLess -> failure x
  TidyParser.Abs.RLessEqual -> failure x
  TidyParser.Abs.RGreater -> failure x
  TidyParser.Abs.RGreaterEqual -> failure x
  TidyParser.Abs.REqual -> failure x
  TidyParser.Abs.RNotEqual -> failure x
transBooleanOperator :: TidyParser.Abs.BooleanOperator -> Result
transBooleanOperator x = case x of
  TidyParser.Abs.BAnd -> failure x
  TidyParser.Abs.BOr -> failure x

