name:                Tidy
version:             0.1.0.0
github:              "gerardd33/Tidy"
license:             BSD3
author:              "Gerard Dróżdż"
maintainer:          "example@example.com"
copyright:           "2021 Gerard Dróżdż"

# Metadata used when publishing your package
# synopsis:            The Tidy programming language
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/gerardd33/Tidy#readme

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- directory
- containers

library:
  source-dirs: src

executables:
  Tidy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tidy

tests:
  Tidy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tidy
